server:
  port: 8080

spring:
  # spring datasource configuration
  datasource:
    driver-class-name: org.h2.Driver
    username: 'sa'
    password: 'sa'
    url: 'jdbc:h2:mem:my_app'  # The JDBC URL for H2, 'mem:', means that the data is stored in memory, 'my_app:' means that the name of the db is 'my_app'
  sql:
    init.mode: always
  h2:
    console:
      enabled: true
      path: '/h2' # url path for using h2-console
  jpa:
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate 

# Setting SpringDoc OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html